image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
   - chmod +x gradlew
   - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
 paths:
   - .gradle/wrapper
   - .gradle/caches
   - build/

stages:
  - build
  - develop
  - deploy

build:
  stage: build
  only:
  - master
  script:
  - ./gradlew clean
  - ./gradlew build
  - echo "build"
  artifacts:
    paths:
    - build/libs/*.jar
